language: rust
sudo: false
matrix:
  include:
    - rust: 1.15.0
    - rust: stable
    - rust: beta
    - rust: nightly
branches:
  only:
    - master
script:
  - |
      cargo build --verbose --no-default-features &&
      cargo build --verbose --features "$FEATURES" &&
      cargo test --verbose --features "$FEATURES" &&
      cargo test --release --verbose --features "$FEATURES"
